### ISSUE TITLE
[Good first issue | Feature]Add a Multi-Table Auto-Modify Processor

### ISSUE THREAD

**Issue by Z712023** [hitsz-ids/synthetic-data-generator#108]
### Problem

When modeling multi-table data, I've observed that real-world data often doesn't satisfy foreign key constraints. For example: `parents_id=[1,2,3], children_id=[1,2]`, or `parents_id=[1,2,3], children_id=[1,2,3,4]`. 

I wish this tool could automatically assist me in cleaning the data, ensuring that foreign keys exist in both the parent and child tables (e.g., `parents_id=[1,2], children_id=[1,2]`). 

In this way, the data used for multi-table simulation modeling can accurately reflect the associative relationships of foreign keys.

### Proposed Solution

Retain only the intersection of foreign keys between the parent table and the child table.

$$ID_{remain} = ID_{parent} \Cap ID_{child}$$

### Additional context

TBD

**Comment by c3kimball** [comment]
I'd like to help with this issue, but I have a few questions:
1. Which file would this be implemented in or is a new file necessary?
2. What do you mean by multi table data? do you have an example data set in which this issue would be useful for?
3. I'd like to more about the foreign key constraint, what it is and how to use it.

Thank you

**Comment by Z712023** [comment]
I realize that the code here has already implemented the logic for the issue.

**Comment by jalr4ever** [comment]
@Z712023 This issue has been resolved and will be closed.
