### ISSUE TITLE
[Good first issue | Feature]Ensure Uniqueness of Composite Primary Key

### ISSUE THREAD

**Issue by Z712023** [hitsz-ids/synthetic-data-generator#109]
### Problem

This tool aims to support composite primary keys, but it seems that it does not guarantee the uniqueness of composite primary keys.

### Proposed Solution

Add validation to the metadata to ensure the uniqueness of composite primary keys during validation.

### Additional context

TBD

**Comment by jalr4ever** [comment]
After our assessment ( @MooooCat ) , this task is not aligned with our goals and direction, so we are closing this ISSUE and will no longer pursue it.

**Comment by jalr4ever** [comment]
> After our assessment ( @MooooCat ) , this task is not aligned with our goals and direction, so we are closing this ISSUE and will no longer pursue it.

This is a boundary issue of SDG, which is more like a problem in the field of data cleaning.
