### ISSUE TITLE
[Good first issue | Feature] Synthesize specific types of IDs

### ISSUE THREAD

**Issue by Z712023** [hitsz-ids/synthetic-data-generator#120]
### Problem

Table data often includes special ID fields, such as a fixed string "AXBSAX" followed by a variable string X, where the fixed string holds a static physical meaning and X increments in quantity, such as "0001", "0002", and so on.

### Proposed Solution
Using regular expressions to analyze the ID format, synthesize different meaningful segments while preserving the static meaning of the original ID field.

We can consider two conditions and handle them separately:

1. The field has no  semantic meaning
(1) Determine the number of unique types.
(2) Use Faker (Note: Faker-generated fields may not preserve the semantic meaning of the original ID field).
2. The field is associated with other attributes and has simulation value
We need to preserve the original field's semantics:
(1) If the ID field carries additional information, abstract it into a new column.
(2) Use the data fitted by the model to guide the generation of Faker.
(3) Exclude in post-processing.

**Comment by Devansh-Kushwaha** [comment]
I can help in adding this feature.
Assign me

**Comment by jalr4ever** [comment]
After our assessment, this task is not aligned with our goals and direction, so we are closing this ISSUE and will no longer pursue it.
