### ISSUE TITLE
[Bug] Metadata's `_extend` missing when saving Metadata to disk (in Json)

### ISSUE THREAD

**Issue by MooooCat** [hitsz-ids/synthetic-data-generator#136]
## Description

Metadata's `_extend` is missing when saving Metadata to disk (in Json). 

## Reproduce

```python
# import packages 
import pandas as pd 
from pathlib import Path
from sdgx.data_models.metadata import Metadata
from sdgx.utils import download_demo_data

# get a metadata, I use a demo dataset 
# every dataset is OK 
p = download_demo_data()
df = pd.read_csv(p)
m = Metadata.from_dataframe(df)

# I add a k-v pair 
# this will add the the  `.extend`  field 
m.add('a', "something") 
# then save the model 
m.save(Path('here.json'))

print(m.get('a'))
"""The output is:
{'something'}
"""

# load the model from disk 
n = Metadata.load(Path("here.json"))
# the value "something" is missing
print(n.get('a'))
"""The output is:
set()
"""
# the `_extend`is empty 
print(n._extend)
''' The output is :
defaultdict(<class 'set'>, {})
'''

```

## Expected behavior

```python
# load the model from disk 
n = Metadata.load(Path("here.json"))
# the value "something" is missing
print(n.get('a'))
"""The expected output should be:
{'something'}
```

## Context

- Operating System and version: macOS 14.2.1（23C71）+ python 3.9
- Browser and version(if necessary):  - 
- Which version are you using: 0.1.5  / 0.1.6 dev0 

I initially think this bug is related to the `model_dump_json()` method in `pydantic.BaseModel`. 

The json str output by this method does not contain `_extend`. 

Maybe it is related to the fact that _extend is a private member of the class ?

**Comment by Wh1isper** [comment]
Nice catch！

The `_extend` contains a lot of information, perhaps we could add a new field to let the user choose which attributes should be saved.

We could start by saving all attributes, given that they shouldn't be too big at the moment.
