### ISSUE TITLE
Information Data Preprocessing

### ISSUE THREAD

**Issue by kajpetersen** [hitsz-ids/synthetic-data-generator#152]
### ❓Search before asking

I have searched for issues similar to this one.

### ❓Description

Is it possible to get/find the code that is used for the preprocessing of the dataset? After evaluating the code, I saw that there is almost no correlation anymore and I was wondering how this was done.

**Comment by MooooCat** [comment]
Good morning! thank you for this question @kajpetersen 

I am currently working on this part. 

The specific branch is`feature-intro-data-processor`, [the link](https://github.com/hitsz-ids/synthetic-data-generator/tree/feature-intro-data-processor).

It is expected to be merged into the main branch next week.

The data processor will include two parts: Data Pre-processing and Data Post-processing, and support the plug-in system.

**Comment by MooooCat** [comment]
hi @kajpetersen 

please check the [data processor](https://github.com/hitsz-ids/synthetic-data-generator/tree/main/sdgx/data_processors) on our lastest released version.
