### ISSUE TITLE
[Good First Issue | Document] Add metadata code example in ipynb

### ISSUE THREAD

**Issue by MooooCat** [hitsz-ids/synthetic-data-generator#153]
### 🚅Search before asking

I have searched for issues similar to this one.

### 🚅Description

Adding metadata‘ code usage examples, an ipython notebook is preferred.

### 🏕Solution(*optional*)

There are some examples for reference in the sdgx documentation and unit tests. 

Add detailed descriptions in the ipython notebook.

**Comment by pojith** [comment]
can i take this task?

**Comment by MooooCat** [comment]
Hi pojith,Sure. Feel free to open a PR any time :)The .ipynb can be placed in example/ dir.從我的iPhone傳送pojith raj R ***@***.***>於2024年3月11日 22:57寫道：﻿
can i take this task?

**Comment by MooooCat** [comment]
> can i take this task?

Hi pojith, @pojith 

Sure. 

Feel free to open a PR any time :)

The .ipynb can be placed in example/ dir.
