### ISSUE TITLE
时序数据生成功能

### ISSUE THREAD

**Issue by twodonkeys** [hitsz-ids/synthetic-data-generator#170]
各位大佬，我想通过自己的各地区项目数据（时间，地区，天气，园区类型，和用电负荷等）训练模型，生成典型日的数据，不知道贵框架能否实现~~

### 使用场景：
①“帮我生成一份 北京地区 8月份 工业园区 某一阴天典型日 一天24小时的温度，湿度，辐照度，用电负荷等数据。”
②然后会生成一份24小时数据：
![image](https://github.com/hitsz-ids/synthetic-data-generator/assets/26646386/217c420d-3349-4f2e-872c-6930d6d1e7b0)

### 看到其他库有类似功能：
https://colab.research.google.com/drive/1YLk2uwn8yrSRPy0soEeJwu8Hdk_tGTlE?usp=sharing#scrollTo=8bORDkGXJcgr

**Comment by MooooCat** [comment]
Hi @twodonkeys , 

We have received your PR and thank you for your valuable content.

If we will support the feature you proposed, after conducting a technical evaluation, we will add an Issue tagged Feature/SDG-Feature to describe the precise newly added technical feature, and keep you updated in subsequent conversations on this Issue :)

**Comment by MooooCat** [comment]
@twodonkeys 

可否提供一份图中数据的csv版本（应包含尽量多的数据条目）供技术人员进行分析与实验？

Could you provide a csv version of this data in the figure (which should contain as many data entries as possible) for technical staff to analyze and experiment?

**Comment by Wh1isper** [comment]
只要通过对数据进行分组，应该可以实现。

就统计模型而言，如果将历年北京8月1日的天气整理成一张表，通过模型训练，应该可以生成无数个符合分布的背景8月1日的天气，将这个过程针对31天重复31次，即可获得无数组仿真数据。

**Comment by twodonkeys** [comment]
> @twodonkeys
> 
> 可否提供一份图中数据的csv版本（应包含尽量多的数据条目）供技术人员进行分析与实验？
> 
> Could you provide a csv version of this data in the figure (which should contain as many data entries as possible) for technical staff to analyze and experiment?
[0-公共数据-光照资源数据1.20 V2 (2).xlsx](https://github.com/hitsz-ids/synthetic-data-generator/files/15004904/0-.-.1.20.V2.2.xlsx)
类似这种类型的数据，每天的天气情况，还有当天的一些气象标签，我可以用气象标签生成符合气象特征的数据。

**Comment by MooooCat** [comment]
> 就统计模型而言，最简单的方式或许可以如果将历年北京8月1日的天气整理成一张表，通过模型训练，应该可以生成无数个符合分布的背景8月1日的天气，将这个过程针对31天重复31次，即可获得无数组仿真数据。

这种方法应该是OK的，但是对于很多用户而言，可能获得如此多 / 准确的数据可能并不是太容易。

如果仅有一年的数据，其实这一年的数据是能够有很多参考价值的，有一些经典的统计学算法来解决这个问题，例如：

- 自回归移动平均模型（ARMA）
- 自回归整合移动平均模型（ARIMA）
- 季节性自回归整合移动平均模型（SARIMA）
- 等

此类通过分析季节性（不同于周期性）、周期性、趋势等时间序列特征，来生成数据，这种方法可能可以需要更少的数据。

我感觉这些算法或许更适合解决这个问题中的一列，例如温度、湿度等。

也许可以开发一种算法，已知一些特征数值、补全其他特征数值的算法，这应该是可行的。

再结合时间序列等经典方法，也许可以更优雅地解决这一问题。
