### ISSUE TITLE
Does the WeChat QR code expire? How can I add it to the user group?

### ISSUE THREAD

**Issue by Can1dance** [hitsz-ids/synthetic-data-generator#196]
### ❓Search before asking

Does the WeChat QR code expire? How can I add it to the user group?

**Comment by MooooCat** [comment]
Thank you for your interest in joining our WeChat group. 

The QR code has been updated. We appreciate your understanding and look forward to having you in the group.

Please scan the new QR code provided in the README and README_ZH_CN files to join. 

 If you encounter any issues, don't hesitate to open an issue for assistance : )
