### ISSUE TITLE
是否有专门针对中文数据的隐私保护转换器？

### ISSUE THREAD

**Issue by sqh539** [hitsz-ids/synthetic-data-generator#222]
描述
我在处理包含中文字段的数据集时，需要确保数据的隐私性。具体来说，我希望能够对数据集中包含敏感信息的字段进行脱敏处理，同时保持数据的基本统计特性不变。我正在使用 sdgx 库来进行数据处理，但我还没有找到适用于中文数据类型的转换器或格式化器。

具体问题：

是否有专门针对中文数据的隐私保护转换器？

环境信息：

Python 版本：3.11
sdgx 库版本：最新版
操作系统：Linux
已尝试的方法：

我已经尝试查找了 sdgx 库的文档，但没有找到关于中文数据隐私保护的具体说明。

预期结果：

希望找到一种方法，能够在保持数据集统计特性的同时，对中文字段进行有效的隐私保护处理，包括使用伪匿名的形式来保持一定的数据特性。

**Comment by MooooCat** [comment]
Hello! @sqh539 

Thank you for your interest in SDG.

Currently, our documentation is not detailed enough and is slightly outdated.

Regarding your questions, I will organize them and then provide you with the necessary information. I have been quite busy with work recently, so it will take a little time.

**Comment by MooooCat** [comment]
Hi @sqh539

The answer is YES.

You can check https://github.com/hitsz-ids/synthetic-data-generator/tree/main/sdgx/data_processors/generators. In the generators, currently, we have re-generated some Chinese PII information (Mainland China ID, mobile phone, Chinese names, and Chinese  company names) as well as email addresses, meaning that these PII (privacy) information from the original data will not appear in the synthetic data output by SDG.

The data types currently supported do not actually cover all types that can be identified by the inspector (it will take some time to continue updating). 

If you urgently need to cover certain data types, we warmly welcome you to raise an Issue to add your requirements, and we are even more welcoming if you contribute through PRs to help us enhance the functionality of SDG.

**Comment by sqh539** [comment]
> Hi @sqh539
> 
> The answer is YES.
> 
> You can check [link](https://github.com/hitsz-ids/synthetic-data-generator/tree/main/sdgx/data_processors/generators). In the generators, currently, we have re-generated some Chinese PII information (Mainland China ID, mobile phone, Chinese names, and Chinese company names) as well as email addresses, meaning that these PII (privacy) information from the original data will not appear in the synthetic data output by SDG.
> 
> The data types currently supported do not actually cover all types that can be identified by the inspector (it will take some time to continue updating).
> 
> If you urgently need to cover certain data types, we warmly welcome you to raise an Issue to add your requirements, and we are even more welcoming if you contribute through PRs to help us enhance the functionality of SDG.
> 
> 答案是肯定的。
> 
> 你可以查看 [link](https://github.com/hitsz-ids/synthetic-data-generator/tree/main/sdgx/data_processors/generators)。在SDG中，目前我们已经重新生成了一些中文个人身份信息（中国大陆身份证、手机号码、中文名字和中文名公司名称），以及电子邮件地址，这意味着原始数据中的这些个人身份信息（隐私信息）不会出现在SDG输出的合成数据中。
> 
> 目前支持的数据类型，实际上并没有涵盖检查器可以识别的所有类型（继续更新还需要一些时间）。
> 
> 如果你急需覆盖某些数据类型，我们非常欢迎你提出问题（Issue）来增加你的需求，如果你能通过PR（Pull Request）的方式帮助我们增强SDG的功能，我们更是热烈欢迎。

非常感谢您的及时回复。
目前，我正处于熟悉和运用代码的初步阶段。
未来，一旦我具备了相应的开发能力，我将非常乐意为项目贡献我的代码。

**Comment by jalr4ever** [comment]
The problem seems to have been resolved.
