### ISSUE TITLE
Missing examples of connecting and loading pandas dataframes

### ISSUE THREAD

**Issue by yimingli** [hitsz-ids/synthetic-data-generator#246]
### ❓Search before asking

I have searched for issues similar to this one.

### ❓Description

I'm not sure whether it's a feature request or documentation enhancement, so posing it as a question for now.

I looked through all the examples in the repo, but only found examples using `CsvConnector`. Curious how to connect and load data that are not csv, for example, how to use a pandas dataframe. This is a common use case, because we often read data from some database or cloud storage (ie non-csv).

**Comment by jalr4ever** [comment]
@yimingli  Hi there. 

I think this PR(https://github.com/hitsz-ids/synthetic-data-generator/pull/247) contains the feature `DataFrameConnector` you need,  coming soon!

**Comment by cyantangerine** [comment]
Before this PR merged, i think you can use GeneratorConnector instead.
````
def generator():
    yield df.copy()
touse = GeneratorConnector(generator)
````

**Comment by jalr4ever** [comment]
Now we support `DataFrameConnector` in new release `0.2.4` just like this:
```python
from pathlib import Path

path_obj = Path(file_path)

# Create a data connector and data loader for large csv data
# SDG will load data with chunk, can reduce memory usage.
data_connector = CsvConnector(path=path_obj)
# For small data you can use DataFrameConnector
# from sdgx.data_connectors.dataframe_connector import DataFrameConnector
# data_connector = DataFrameConnector(dataframe)
data_loader = DataLoader(data_connector)
```


Check [this](https://github.com/hitsz-ids/synthetic-data-generator/blob/main/example/sdgx_example_metadata.ipynb) out for full code!
