### ISSUE TITLE
[Feature]🌌Jensen–Shannon divergence Implementation

### ISSUE THREAD

**Issue by MooooCat** [hitsz-ids/synthetic-data-generator#40]
### 🚅Search before asking

I have searched for issues similar to this one.

### 🚅Description

In probability theory and statistics, the [Jensen–Shannon divergence](https://en.wikipedia.org/wiki/Jensen–Shannon_divergence), “JS散度” in Chinese, is a method of measuring the similarity between two probability distributions. It is also known as information radius (IRad) or total divergence to the average. It is based on the Kullback–Leibler divergence, with some notable (and useful) differences, including that it is symmetric and it always has a finite value. The square root of the Jensen–Shannon divergence is a metric often referred to as Jensen–Shannon distance.

The value range of JSD is [0,1], when two distributions are similar, JSD approaches 0. If the two distributions do not overlap at all, JSD is equal to the constant 1. The closer the JSD to 0, the more similar the distribution, thus the higher the quality of the synthetic data.

### 🏕Solution

Implement the calculation of Jensen–Shannon divergence by coding or calling methods in existing modules. The implementation code should be located in the `sdgx/metrics` directory, and the class implementation should inherit from the base class in `sdgx/metrics/base.py`.

### 🍰Detail

In addition to implementing JSD, the demo code in `example/` and the related code in `Readme.md` should also be added.

Since this is the first metric method implemented, the base class can be modified if necessary to make it more suitable for various metric calculations.

**Comment by Guo-Yunzhe** [comment]
I will work on this issue.

**Comment by MooooCat** [comment]
You can try this issue first to implement this metric for single-table evaluation.

**Comment by Wh1isper** [comment]
@MooooCat Hello. Might this issue be closed? Given that JSD has been merged into the main branch.

**Comment by MooooCat** [comment]
> @MooooCat Hello. Might this issue be closed? Given that JSD has been merged into the main branch.

This issue can be closed.
