### ISSUE TITLE
[BOT] Add contributors

### ISSUE THREAD

**Issue by Wh1isper** [hitsz-ids/synthetic-data-generator#52]
@all-contributors
please add @Wh1isper for code.
please add @MooooCat for code.
please add @joeyscave for code.

**Comment by wunder957** [comment]
https://github.com/all-contributors
please add @Wh1isper for code.
please add @MooooCat for code.
please add @joeyscave for code.

**Comment by wunder957** [comment]
@all-contributors
please add @Wh1isper for code.
please add @MooooCat for code.
please add @joeyscave for code.

**Comment by wunder957** [comment]
@all-contributors
please add @Wh1isper for code.
please add @MooooCat for code.
please add @joeyscave for code.

**Comment by Wh1isper** [comment]
@all-contributors
please add @Wh1isper for code.
please add @MooooCat for code.
please add @joeyscave for code.
