### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by Wh1isper** [hitsz-ids/synthetic-data-generator#62]
Known blocking issues:
- [x] https://github.com/pytorch/pytorch/issues/110436

**Comment by MooooCat** [comment]
In issue https://github.com/pytorch/pytorch/issues/110436, pytorch 2.2 preview can almost support python 3.12 (some are not fully tested).

I'll continue to track torch 2.2's support for python 3.12, it should be fine, and we will add support by then.

**Comment by Wh1isper** [comment]
It's easy to test python 3.12 by adding 3.12 in here: https://github.com/hitsz-ids/synthetic-data-generator/blob/main/.github/workflows/python-package.yml#L15

I just opened an PR on it https://github.com/hitsz-ids/synthetic-data-generator/pull/141
