### ISSUE TITLE
[Good first issue | Feature] Implement a smarter `DatetimeInspector`

### ISSUE THREAD

**Issue by MooooCat** [hitsz-ids/synthetic-data-generator#95]
### 🚅Search before asking

I have searched for issues similar to this one.

### 🚅Description

Update `class DatetimeInspector(Inspector)` in `sdgx/data_models/inspectors/datetime.py` to achieve: 

- Allow preset common datetime format string, such as: "%Y/%m/%d", "%Y-%m-%d", etc.;
- Allow users to specify uncommon but clear datetime format string: "%b-%d-%Y", etc.;

Same as the existing `DatetimeInspector`, after running the `fit` method, you can infer which columns belong to the Datetime type. After implementing this Issue, `DatetimeInspector` can output the specific format strings of some of the columns (not all of them), will help improve the quality of synthetic data.

### 🏕Solution(*optional*)

Briefly speaking, the following steps are required:

- Modify member variables, add preset Datetime format string;
- Modify the `__init__` method, add parameters in user-specified format;
- Modify the `fit` method, add the  Datetime format string matching steps;
- Modify the `inspect` method and add the output Datetime format string, which will be passed to metadata;
- During the implementation process, performance also needs to noticed.

**Comment by Femi-lawal** [comment]
Hi @MooooCat please can I work on this?

**Comment by MooooCat** [comment]
Hi Lawal, 

Sure, feel free to open a PR any time.

@Femi-lawal

**Comment by Wh1isper** [comment]
Implemented in #125
